/**
 * Electron Main Process Entrypoint for AutoFiller AI.
 *
 * Owns window creation, security hardening, backend supervision, the agent controller,
 * and lifecycle cleanup.
 */

import { app, BrowserWindow, session, shell } from 'electron';
import path from 'path';
import fs from 'fs';

import { AgentController } from './agent/AgentController';
import { registerIpcHandlers } from './ipc/ipcHandlers';
import { BackendClient } from './services/BackendClient';
import { SecretStore } from './services/SecretStore';

/** Base URL of the local Python backend. */
const BACKEND_BASE_URL = process.env.AUTOFILLER_BACKEND_URL || process.env.FORMPILOT_BACKEND_URL || 'http://127.0.0.1:8000';

/** Maximum time to wait for the backend to become healthy. */
const BACKEND_HEALTH_TIMEOUT_MS = 20000;

let mainWindow: BrowserWindow | null = null;
let agentController: AgentController | null = null;
let secretStore: SecretStore | null = null;
let backendProcess: import('child_process').ChildProcess | null = null;

/** CSP applied to the renderer. Blocks remote code and inline script execution. */
const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self' data:",
  "connect-src 'self' " + BACKEND_BASE_URL,
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join('; ');

/**
 * Resolve the internal operator token shared with the backend.
 *
 * Prefers an explicitly configured token, then the OS-encrypted store, then the
 * per-install token file generated by the backend.
 *
 * @returns The operator token, or an empty string when none can be found.
 */
function resolveOperatorToken(): string {
  const configured = (process.env.AUTOFILLER_INTERNAL_KEY || process.env.FORMPILOT_INTERNAL_KEY || '').trim();
  if (configured) {
    return configured;
  }

  if (secretStore) {
    const stored = secretStore.loadToken();
    if (stored) {
      return stored;
    }
  }

  // Fall back to the token the backend generates on first run so a fresh install
  // authenticates without manual configuration.
  const candidates = [
    path.join(__dirname, '../../backend/.autofiller_token'),
    path.join(process.resourcesPath || '', 'backend/.autofiller_token'),
    path.join(__dirname, '../../backend/.formpilot_token'),
    path.join(process.resourcesPath || '', 'backend/.formpilot_token'),
  ];
  for (const candidate of candidates) {
    try {
      if (candidate && fs.existsSync(candidate)) {
        const token = fs.readFileSync(candidate, 'utf-8').trim();
        if (token) {
          if (secretStore && secretStore.isEncryptionAvailable()) {
            try {
              secretStore.saveToken(token);
            } catch {
              // Non-fatal: continue using the on-disk token for this session.
            }
          }
          return token;
        }
      }
    } catch {
      // Try the next candidate.
    }
  }
  return '';
}

/**
 * Poll the backend health endpoint until it reports healthy or the timeout elapses.
 *
 * @param client Backend client used for the health probe.
 * @returns True when the backend became healthy.
 */
async function waitForBackend(client: BackendClient): Promise<boolean> {
  const deadline = Date.now() + BACKEND_HEALTH_TIMEOUT_MS;
  while (Date.now() < deadline) {
    if (await client.health()) {
      return true;
    }
    await new Promise((resolve) => setTimeout(resolve, 400));
  }
  return false;
}

/**
 * Launch the bundled Python backend when one is available.
 *
 * Never starts a shell; runs the interpreter directly with a fixed argument list.
 */
function spawnBackend(): void {
  const isPackaged = app.isPackaged;
  const candidatePaths = isPackaged
    ? [path.join(process.resourcesPath, 'backend', 'formpilot-backend.exe')]
    : [path.join(__dirname, '../../venv/Scripts/python.exe'), path.join(__dirname, '../../venv/bin/python')];

  const executable = candidatePaths.find((candidate) => candidate && fs.existsSync(candidate));
  if (!executable) {
    console.warn('No bundled backend executable found; expecting an external backend.');
    return;
  }

  try {
    const { spawn } = require('child_process');
    const args = isPackaged
      ? []
      : ['-m', 'uvicorn', 'core.apis.api:app', '--app-dir', 'backend', '--host', '127.0.0.1', '--port', '8000'];
    const child = spawn(executable, args, {
      cwd: path.join(__dirname, '../..'),
      stdio: 'ignore',
      windowsHide: true,
    });
    child.on('error', (error: Error) => {
      console.error('Backend process failed to start:', error);
    });
    backendProcess = child;
  } catch (error) {
    console.error('Could not start backend process:', error);
  }
}

/**
 * Create the main application window and wire the agent controller.
 */
async function createWindow(): Promise<void> {
  secretStore = new SecretStore();
  const operatorToken = resolveOperatorToken();
  const backendClient = new BackendClient(operatorToken, BACKEND_BASE_URL);

  agentController = new AgentController(backendClient);

  mainWindow = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 1100,
    minHeight: 700,
    title: 'AutoFiller AI',
    backgroundColor: '#090d16',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
  });

  registerIpcHandlers(mainWindow, agentController, secretStore);

  // Apply a strict CSP and block all outbound navigation and window creation.
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [CONTENT_SECURITY_POLICY],
      },
    });
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url).catch(() => undefined);
    return { action: 'deny' };
  });

  mainWindow.webContents.on('will-navigate', (event, url) => {
    const isDevServer = url.startsWith('http://localhost:5173') || url.startsWith('http://127.0.0.1:5173');
    if (!isDevServer && !url.startsWith('file://')) {
      event.preventDefault();
      console.warn(`Blocked renderer navigation to ${url}`);
    }
  });

  const isDev = !app.isPackaged;
  if (isDev && process.env.VITE_DEV_SERVER_URL) {
    await mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    const indexPath = path.join(__dirname, '../dist/index.html');
    if (fs.existsSync(indexPath)) {
      await mainWindow.loadFile(indexPath);
    } else if (isDev) {
      await mainWindow.loadURL('http://localhost:5173');
    } else {
      console.error('Renderer bundle not found. Run the build step before packaging.');
    }
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  if (!(await waitForBackend(backendClient))) {
    console.warn('Backend did not report healthy within the startup window.');
  }
}

/**
 * Shut down the agent, browser, and any backend process we started.
 */
async function shutdown(): Promise<void> {
  if (agentController) {
    await agentController.cleanup().catch(() => undefined);
  }
  if (backendProcess && !backendProcess.killed) {
    backendProcess.kill();
    backendProcess = null;
  }
}

app.whenReady().then(() => {
  spawnBackend();
  return createWindow();
});

app.on('window-all-closed', async () => {
  if (agentController) {
    agentController.disposeListeners();
  }
  await shutdown();
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('before-quit', async () => {
  await shutdown();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    void createWindow();
  }
});
